# Generated by Django 6.0 on 2026-01-03 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0002_alter_jobapplication_options_jobapplication_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interview_type', models.CharField(choices=[('phone', 'Phone'), ('technical', 'Technical'), ('onsite', 'Onsite')], max_length=20)),
                ('date', models.DateTimeField()),
                ('outcome', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='jobs.jobapplication')),
            ],
        ),
    ]
