# Generated by Django 6.0 on 2026-01-02 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobapplication',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='source',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
